# Generated by Django 3.2.7 on 2022-07-31 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(default='', max_length=255)),
                ('text', models.CharField(default='', max_length=4095)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='posts',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='accounts.post'),
        ),
    ]
