# Generated by Django 3.2.7 on 2022-07-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='media/default/default.jpg', upload_to='media/avatars/'),
        ),
    ]
