# Generated by Django 3.2.7 on 2022-07-31 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='posts',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='accounts.post'),
        ),
    ]
