# Generated by Django 3.2.7 on 2022-07-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_post_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(null=True, to='accounts.PostImage'),
        ),
    ]
