# Generated by Django 3.2.7 on 2022-08-02 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_postimage_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
