# Generated by Django 3.2.7 on 2022-08-02 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_rename_owner_post_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
