# Generated by Django 3.2.7 on 2022-08-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_rename_owner_id_post_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='liked',
            field=models.ManyToManyField(blank=True, to='accounts.Post'),
        ),
    ]
