# Generated by Django 3.2.7 on 2022-08-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_customuser_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.Post'),
        ),
    ]
